import fs from 'node:fs';
const base='productions/nhung-phat-minh-thay-doi-the-gioi',checkedDate='2026-10-04';
const sources=[
 {id:'R01',title:'WHO — History of smallpox vaccination',url:'https://www.who.int/news-room/spotlight/history-of-vaccination/history-of-smallpox-vaccination',sceneIds:['I197','I198','I205','I206'],status:'read',claim:'Jenner thử nghiệm năm 1796; WHO tuyên bố thanh toán đậu mùa năm 1980. Lịch sử trước Jenner và nỗ lực phối hợp toàn cầu được phân biệt.'},
 {id:'R02',title:'CDC — History of Drinking Water Treatment',url:'https://archive.cdc.gov/www_cdc_gov/healthywater/drinking/history.html',sceneIds:['I173','I174'],status:'read',claim:'Jersey City bắt đầu khử trùng nước cộng đồng thường xuyên năm 1908; xử lý nước là thành tựu y tế công cộng quan trọng. Nguồn lưu trữ, không dùng số dịch tễ cũ làm số liệu hiện nay.'},
 {id:'R03',title:'Computer History Museum — Point-contact transistor',url:'https://www.computerhistory.org/siliconengine/invention-of-the-point-contact-transistor/',sceneIds:['I271','I272','I273'],status:'read',claim:'Bardeen và Brattain tạo bộ khuếch đại bán dẫn tiếp xúc điểm tại Bell Labs trong tháng 12 năm 1947.'},
 {id:'R04',title:'Internet Society — A Brief History of the Internet',url:'https://www.internetsociety.org/internet/history-internet/brief-history-internet/',sceneIds:['I303','I305','I306','I307','I309','I353'],status:'read',claim:'Kiến trúc mạng mở và đóng góp nhiều nhóm; ARPANET chuyển từ NCP sang TCP/IP ngày 1/1/1983; email có vai trò sớm.'},
 {id:'R05',title:'USNO — NAVSTAR Global Positioning System',url:'https://www.gulflink.osd.mil/khamisiyah_ii/khamisiyah_ii_refs/n15en239/gpsinfo.html',sceneIds:['I321','I322','I323','I324','I325'],status:'read',claim:'Phân biệt IOC 1993 và FOC 1995. Tín hiệu vệ tinh mang thông tin quỹ đạo và thời gian. Đã sửa S321, không kế thừa mốc đầy đủ 1993 trong bản gốc.'},
 {id:'R06',title:'Smithsonian — 1903 Wright Flyer',url:'https://airandspace.si.edu/collection-objects/1903-wright-flyer/nasm_A19610048000',sceneIds:['I243','I244','I245'],status:'search-excerpt',claim:'Kết quả nguồn bảo tàng xác nhận chương trình nghiên cứu và ngày bay 17/12/1903. Địa điểm chính xác được bổ sung từ NPS.'},
 {id:'R07',title:'National Park Service — Wright Flyer at Kill Devil Hills',url:'https://npgallery.nps.gov/AssetDetail/7ff3aba781ce4d9c8aa9c64f84bc449a',sceneIds:['I244'],status:'search-excerpt',claim:'Ảnh và mô tả NPS ghi Flyer tại Big Kill Devil Hill và chuyến bay ngày 17/12/1903.'},
 {id:'R08',title:'Nobel Prize — Carl Bosch Facts',url:'https://www.nobelprize.org/prizes/chemistry/1931/bosch/facts/',sceneIds:['I213','I214','I215','I216'],status:'search-excerpt',claim:'Haber phát triển tổng hợp amoniac; Bosch mở rộng quy trình áp suất cao lên công nghiệp khoảng năm 1913.'},
 {id:'R09',title:'IEA — Ammonia Technology Roadmap',url:'https://www.iea.org/reports/ammonia-technology-roadmap/executive-summary',sceneIds:['I219','I220','I224'],status:'read',claim:'Vai trò sản xuất phân bón và các lộ trình giảm phát thải. Đây là roadmap 2021, không bằng chứng mọi mục tiêu đã được thực hiện vào 2026; giữ mô tả hướng nghiên cứu, bỏ số dân phụ thuộc chưa kiểm chứng.'},
 {id:'R10',title:'WHO — Antibiotic resistance information',url:'https://www.who.int/docs/librariesprovider2/default-document-library/what-you-need-to-know-about-antibiotic-resistance-eng-%281%29.pdf?sfvrsn=5d89a70_6',sceneIds:['I265','I266','I267'],status:'search-excerpt',claim:'Kháng sinh tác động lên vi khuẩn, không virus; dùng không cần thiết thúc đẩy kháng thuốc. Không đưa tư vấn điều trị cá nhân.'},
 {id:'R11',title:'Nobel Prize — Medicine 1945',url:'https://www.nobelprize.org/prizes/medicine/1945/summary/',sceneIds:['I257','I259','I352'],status:'search-excerpt-after-open-error',claim:'Nguồn Nobel ghi giải 1945 chung cho Fleming, Chain và Florey. Lần mở trực tiếp lỗi; chỉ sử dụng thông tin trong kết quả tìm kiếm, không nhận đã đọc toàn trang.'},
 {id:'R12',title:'Library of Congress — Who invented the telephone?',url:'https://www.loc.gov/everyday-mysteries/categories/technology/item/who-is-credited-with-inventing-the-telephone',sceneIds:['I153','I154'],status:'search-excerpt-after-open-error',claim:'Bằng sáng chế Bell năm 1876 và tranh chấp với Gray. URL có dấu slash cuối mở lỗi; kết quả nguồn xác nhận giới hạn claim, không quy Bell là người đóng góp duy nhất.'},
 {id:'R13',title:'Smithsonian — Joseph W. Swan',url:'https://americanhistory.si.edu/lighting/bios/swan.htm',sceneIds:['I125','I126','I351'],status:'search-excerpt',claim:'Swan báo cáo thành công cuối 1878, trình diễn đèn tháng 2/1879; Edison có hệ đèn nổi tiếng sau đó. Không suy ra một nhà phát minh duy nhất.'}
].map(s=>({...s,checkedDate}));
fs.writeFileSync(`${base}/sources.json`,JSON.stringify(sources,null,2)+'\n');
fs.writeFileSync(`${base}/sources.md`,'# Nguồn và giới hạn kiểm chứng\n\nNgày đối chiếu: 2026-10-04, Asia/Saigon. Đối chiếu chọn lọc các mốc/claim quan trọng; không nhận 360 câu đã kiểm chứng độc lập. Dữ kiện lịch sử còn lại giữ cách diễn đạt thận trọng từ bản người dùng, cần đối chiếu thêm nếu làm bản xuất bản. Không tái sử dụng tuyên bố “đã đối chiếu nguồn” trong phụ lục như bằng chứng của lượt này. Không tải hay dùng hình bảo tàng làm ảnh giao; toàn bộ tranh được tạo mới.\n\n| ID | Cảnh | Nguồn | Mức truy cập | Claim và giới hạn |\n|---|---|---|---|---|\n'+sources.map(s=>`| ${s.id} | ${s.sceneIds.join(', ')} | [${s.title}](${s.url}) | ${s.status} | ${s.claim} |`).join('\n')+'\n\n## Những mục chưa kiểm chứng độc lập\n\nNiên đại và lịch sử bánh xe, chữ viết, giấy, la bàn, in ấn Đông Á, đồng hồ cơ, Watt, điện báo, động cơ đốt trong, toàn bộ cơ chế lạnh và chi tiết triển khai smartphone chưa được đối chiếu đủ từng câu ở lượt này. Đồ họa công nghệ là mô hình khái niệm. Các phần hiện đại giữ mô tả xu hướng, không thêm số thị phần, lượng người dùng hay hiệu năng có thể đổi. Không dùng link không liên quan như máy khâu ở phụ lục gốc làm nguồn hỗ trợ.\n');
const scenes=JSON.parse(fs.readFileSync(`${base}/storyboard.json`,'utf8'));
for(const s of scenes)s.sourceIds=sources.filter(r=>r.sceneIds.includes(s.id)).map(r=>r.id);
fs.writeFileSync(`${base}/storyboard.json`,JSON.stringify(scenes,null,2)+'\n');
console.log(JSON.stringify({sources:sources.length,scope:'partial verification; access levels explicit'}));
