import fs from 'node:fs';
const base='productions/the-loai-game',sentences=JSON.parse(fs.readFileSync(`${base}/sentences.json`)),scenes=JSON.parse(fs.readFileSync(`${base}/storyboard.json`)),cores={};
for(const s of sentences){const m=s.originalPrompt.match(/^MIO presents (.+?) through (.+)$/);if(m)cores[m[1]]=m[2].replace(/, using GENREWHEEL slices.*$/,'');}
const motifs={GENREWHEEL:'an unlabeled segmented circular wheel of game mechanics icons',SKILLTREE:'a branching diagram of mechanics icons, a conceptual relationship network rather than exact historical chronology',PIXELPORTAL:'a glowing square-pixel portal linking eras of game design',CARTRIDGE:'an unbranded retro game cartridge',GAMEPAD:'an unbranded game controller'};
for(const scene of scenes){if(scene.status!=='pending')continue;const s=sentences.find(x=>x.id===scene.sentenceIds[0]);let p=s.originalPrompt.replace(/ in a polished editorial infographic scene with dynamic depth and no text\.?$/,'').replace(/, using GENREWHEEL slices.*$/,'');const g=p.match(/^A side-by-side visual compares (.+?) with neighboring/),ex=p.match(/^Collage scene of representative examples for (.+?), with MIO/);
 if(g)p=`A close gameplay diagram highlighting ${g[1]} mechanics: ${cores[g[1]]}. Clear action-and-feedback arrows and icons, no invented comparison to an unspecified other genre`;
 if(ex)p=`Original fictional gameplay vignettes illustrating ${ex[1]} mechanics: ${cores[ex[1]]}. Different worlds share the same central mechanic, not authentic screenshots or named franchise characters`;
 p=p.replaceAll('MIO','Mio');for(const[k,v]of Object.entries(motifs))p=p.replaceAll(k,v);
 if(scene.id==='I015')p='Mio compares a simple segmented mechanics wheel with overlapping branches and diverse game worlds, conveying the questions of category boundaries without drawn question marks or written questions';
 if(scene.id==='I079')p='Mio presents a grid tactics battlefield beside individual hero progression branches; the grid is one common design example, not the only form of tactical RPG';
 if(scene.id==='I107')p='Mio presents a player-created adventurer at branching quests and a broad explorable world, an example of role-playing choice rather than a claim that all Western RPGs are alike';
 if(scene.id==='I270')p='An original top-down turn-based dungeon scene with tiles, an anonymous explorer, randomized rooms and a restart loop sits beside overlapping blank classification cards and discussion silhouettes; represent debate over definitions, no authoritative certification seal';
 if(scene.id==='I273')p='Two successive adventure runs share a persistent upgrade tree between them, while each run still contains challenging obstacles; show persistence, not an easy-versus-hard comparison';
 if(scene.id==='I315'||scene.id==='I316'||scene.id==='I317')p='Separate three clearly bounded camera examples: a first-person room puzzle with hands visible, a side-view jumping platform character, and an isometric role-playing party on a tiled landscape. Each is its own gameplay vignette, no conflicting viewpoints in one scene';
 scene.description=p;scene.includesMio=/Mio/.test(p);scene.overlayText=(s.originalPrompt.match(/^MIO presents (.+?) through /)||g||ex)?.[1]?[((s.originalPrompt.match(/^MIO presents (.+?) through /)||g||ex)[1])]:[];
 const prefix=scene.prompt.slice(0,scene.prompt.indexOf(' Scene: ')),tail=scene.prompt.slice(scene.prompt.indexOf(' Conceptual gameplay illustration'));
 scene.prompt=`${prefix} Scene: ${p}. One focused story beat; make the central player action and feedback visually clear. ${scene.includesMio?'Mio is the recurring modern anime guide: short teal bob hair, round glasses, mustard-yellow jacket, brass pocket watch on a chain. She presents the gameplay from outside; she does not wield its weapons.':'No Mio or presenter.'}${tail}`;
}
fs.writeFileSync(`${base}/storyboard.json`,JSON.stringify(scenes,null,2)+'\n');fs.writeFileSync(`${base}/prompts.md`,'# 340 prompt ảnh hiện hành\n\nGiới hạn 200 ảnh đã được người dùng bỏ trong chat. Một câu/một ảnh; chữ thêm sau.\n\n'+scenes.map(s=>`## ${s.id} · ${s.sentenceIds[0]}\n\n${s.prompt}\n`).join('\n'));console.log(JSON.stringify({pending:scenes.filter(s=>s.status==='pending').length}));
