import fs from 'node:fs';
const dir='productions/bia-vi-sinh';
const supplement=`\n## R25 — American Homebrewers Association — Understanding Water for Homebrewing\n\n- [Nguồn ngành trực tiếp](https://homebrewersassociation.org/how-to-brew/understanding-water-for-homebrewing/)\n- Đối chiếu S024: khoáng nước, khả năng đệm và pH ảnh hưởng mash và hương vị. Chỉ diễn giải vai trò cơ bản, không dùng ngưỡng định lượng của bài làm quy tắc chung.\n- Toàn văn mở được ngày 2026-10-02; các phần pH, Alkalinity và Flavor Ions.\n\n## R26 — The Open University — The science of alcohol, 3.2 Bottom fermented beers: lagers\n\n- [Nguồn giáo dục đại học trực tiếp](https://www.open.edu/openlearn/mod/oucontent/view.php?id=97195&section=_unit3.3.2)\n- Đối chiếu S066: tên lager liên quan từ tiếng Đức lagern, nghĩa là lưu trữ. Không dùng trang này để chốt một mốc phát minh hoặc nơi phát minh độc nhất.\n- Toàn văn mở được ngày 2026-10-02; phần 3.2.\n`;
fs.appendFileSync(`${dir}/sources-supplement.md`,supplement);
fs.appendFileSync(`${dir}/sources.md`,`\n## Cập nhật sau kiểm chứng bổ sung\n\nDanh sách claim phía trên là checklist của vòng đầu, không phải toàn bộ đều còn thiếu. Xem [sources-supplement.md](sources-supplement.md): R19–R26 bổ sung công nghệ giảm cồn, tạo mầm bọt, xử lý thành phẩm, hương, thiên lệch nghiên cứu quan sát, ý nghĩa phân loại IARC, khoáng nước và từ nguyên lager. Giới hạn truy cập của từng nguồn vẫn được giữ nguyên; không gọi mô tả lập chỉ mục là đã đọc toàn văn.\n\nS148 giữ ở mức tên gọi có thể khác theo thị trường; chưa chọn quốc gia và không đưa ngưỡng pháp lý chung. Mọi đồ thị/ẩn dụ trong ảnh chỉ là minh họa; hồ sơ không có dữ liệu định lượng để suy ra tỷ lệ hay mức rủi ro từ hình.\n`);
const scenes=JSON.parse(fs.readFileSync(`${dir}/storyboard.json`,'utf8'));
for(const [id,ref] of [['I024','R25'],['I066','R26']]){const scene=scenes.find(x=>x.id===id);scene.sourceIds=[...new Set([...scene.sourceIds,ref])];}
fs.writeFileSync(`${dir}/storyboard.json`,JSON.stringify(scenes,null,2)+'\n');
console.log('Source supplement R25–R26 and scene mappings saved.');
