import fs from 'node:fs';
const p='productions/bia-vi-sinh/';
const s=JSON.parse(fs.readFileSync(p+'storyboard.json','utf8'));
for(const id of ['I015','I017']){const x=s.find(v=>v.id===id);x.status='needs-revision';x.qa={visualReview:id==='I017'?'Incorrect Asian tea workshop, not Egyptian miniature.':'Hop cones intrude into ancient origin scene; remove hops and heat steam from fermentation.'};}
s[14].prompt='One standalone 16:9 2D anime science illustration, cel shaded amber and teal. A simple rough undecorated clay fermentation pot filled with grain liquid in a generic ancient grain-processing shelter. A circular conceptual magnifying window shows oval budding yeast cells. Ancient grain-only scene BEFORE widespread use of hops. ONLY barley, stone tools, ceramic and straw baskets. Absolutely NO hop cones, leaves, rice, coffee, steaming hot liquid, modern equipment, Asian temple roofs or people. Do not copy previous compositions. No text, labels, letters, logos. Keep lower fifth and bottom-right quiet. Asset I015.';
s[16].prompt='One standalone wide 16:9 2D anime illustration of an imagined ANCIENT EGYPTIAN WOODEN MINIATURE bakery and brewery model, museum educational illustration. Obvious small carved wooden figurines with painted reddish-brown skin, simple WHITE LINEN kilts, shaved heads. A small open-top rectangular ochre plaster model with TWO adjacent rooms, grain grinding slab stones, tiny bread loaves, plain tall CLAY fermentation crocks. Elevated three-quarter museum table view, no full-size humans, no living workshop. Inspired by Middle Kingdom material culture, not a replica of the Met object. Absolutely NO Asian clothing, hair buns, bamboo, tea leaves, hop cones, green vegetables, timber barrel workshop, pagoda roofs, stainless steel. No hieroglyphs, labels, text or numbers. Warm amber and dark teal cel shading, quiet lower area and bottom-right. Asset I017.';
fs.writeFileSync(p+'storyboard.json',JSON.stringify(s,null,2)+'\n');
const m=JSON.parse(fs.readFileSync(p+'manifest.json','utf8'));m.progress.verifiedImages=s.filter(x=>x.status==='verified').length;m.progress.needsRevision=2;fs.writeFileSync(p+'manifest.json',JSON.stringify(m,null,2)+'\n');
for(const x of s.filter(x=>['I015','I017'].includes(x.id))){fs.renameSync(x.file,x.file.replace('.png','-v1-rejected.png'));}
console.log(JSON.stringify(s.filter(x=>['I015','I017'].includes(x.id))));
