import fs from 'node:fs';
const b='productions/cac-loai-cong-trinh';
const range=(a,z)=>Array.from({length:z-a+1},(_,i)=>`S${String(a+i).padStart(3,'0')}`);
const entries=[
 ['R01','DOE — Types of Hydropower Plants','https://www.energy.gov/cmei/water/types-hydropower-plants',[...range(17,20),...range(24,35)],'read','Ba dạng vận hành; hồ chứa, chuyển dòng và tích năng; không phải mọi hệ cần đập lớn. Không dùng để xác minh kết cấu đập hay Hoover.'],
 ['R02','FHWA — All About Tunnels','https://www.fhwa.dot.gov/publications/focus/10may/03.cfm',range(91,116),'read','Các nhóm thi công và điều kiện chọn, không xác nhận mọi cấu hình TBM.'],
 ['R03','FHWA — SNBI code mapping','https://www.fhwa.dot.gov/bridge/snbi/codemapping.cfm',range(60,90),'read','Đối chiếu tên nhóm kết cấu; không xác minh toàn bộ sơ đồ lực hay so sánh tính kinh tế.'],
 ['R04','FAA — Airport Design Technical Video Series','https://www.faa.gov/airports/engineering/airport_design/airport_design_technical_videos',[...range(174,177)],'read','Phân biệt runway/taxiway/apron và hình học khu bay; không dùng để khẳng định quy trình kiểm soát không lưu.'],
 ['R05','DOE — Nuclear 101','https://www.energy.gov/ne/articles/nuclear-101-how-does-nuclear-reactor-work',range(233,236),'read','Phân hạch tạo nhiệt rồi phát điện qua tua-bin; cấu hình chu trình phụ thuộc loại lò.'],
 ['R06','DOE — How Do Wind Turbines Work?','https://www.energy.gov/cmei/systems/how-do-wind-turbines-work',range(245,250),'read','Lực khí động quay rotor/máy phát, hệ trên bờ/ngoài khơi; không xác minh kết luận chi phí cho mọi dự án.'],
 ['R07','DOE — Geothermal Electricity Generation','https://www.energy.gov/hgeo/geothermal/geothermal-electricity-generation',range(253,256),'read','Điều kiện nguồn nhiệt/chất lưu/độ thấm và công nghệ; không bảo đảm vận hành liên tục của dự án cụ thể.'],
 ['R08','USACE — Managing Levees','https://levees.sec.usace.army.mil/levee-basics/managing-levees/',[...range(293,294),...range(297,300)],'read','Giảm rủi ro và yêu cầu vận hành, quan trắc, ứng phó khẩn cấp; không loại bỏ toàn bộ rủi ro.'],
 ['R09','EPA — Flow Control Devices','https://www.epa.gov/emergency-response-research/stormwater-management-technologies-flow-control-devices',range(305,308),'read','Phân biệt detention thường khô giữa các trận mưa với retention có hồ thường xuyên. Thuật ngữ địa phương có thể khác.'],
 ['R10','DOE — How Does Solar Work?','https://www.energy.gov/cmei/systems/how-does-solar-work',range(237,244),'read','PV tạo điện trực tiếp; CSP tập trung ánh sáng thành nhiệt.'],
 ['R11','DOE — Inverters and Grid Services','https://www.energy.gov/cmei/systems/solar-integration-inverters-and-grid-services-basics',[...range(237,238)],'read','Bộ nghịch lưu chuyển điện một chiều PV sang xoay chiều cho lưới.'],
 ['R12','EPA — Drinking Water Treatment (archive)','https://archive.epa.gov/water/archive/web/pdf/2009_08_28_sdwa_fs_30ann_treatment_web.pdf',range(271,274),'read','Các công đoạn thông dụng cho nước mặt; lựa chọn công nghệ tùy chất lượng nước. Nguồn lưu trữ, không phải tiêu chuẩn hiện hành.'],
 ['R13','CTBUH — Outrigger study','https://global.ctbuh.org/resources/papers/download/1332-outrigger-system-study-for-tall-building-structure-with-central-core-and-square-floor-plate.pdf',range(201,204),'access-failed','Công cụ không đọc được PDF. Chưa xác minh riêng các câu này bằng nguồn này.'],
 ['R14','USACE — Levee Safety Program','https://www.usace.army.mil/Missions/Civil-Works/Levee-Safety-Program/',[],'access-failed','Lỗi truy cập; dùng R08 thay cho kiểm chứng giảm rủi ro.']
].map(([id,title,url,sentenceIds,status,scope])=>({id,title,url,sentenceIds,status,checkedDate:'2026-10-02',scope}));
fs.writeFileSync(`${b}/sources.json`,JSON.stringify(entries,null,2)+'\n');
fs.writeFileSync(`${b}/sources.md`,'# Nguồn và giới hạn\n\nNgày đối chiếu 02/10/2026. Chỉ dùng nguồn gốc chính thức; trạng thái read có nghĩa đã đọc phần liên quan qua công cụ web, không chứng nhận mọi câu liên kết. Nguồn liên kết theo nhóm nhằm tra cứu, không coi mọi chi tiết nằm trong nguồn.\n\n'+entries.map(e=>`## ${e.id} — ${e.title}\n\n[Trang nguồn](${e.url}) · ${e.status} · ${e.checkedDate}\n\nCâu: ${e.sentenceIds.join(', ')||'Không liên kết'}.\n\n${e.scope}`).join('\n\n')+'\n\n## Chưa đối chiếu độc lập đầy đủ\n\nKết cấu đập và bài toán nền/thấm, sơ đồ lực chi tiết của cầu, đường bộ/đường sắt và kinh tế vận tải, cảng và kiểm soát không lưu, khung nhà và mái nhịp lớn, bệnh viện/data center, nhiệt điện/truyền tải, mạng cống/khử mặn, kè biển/cống triều, công nghiệp/mỏ/giàn/pipeline. Những câu này là diễn giải phổ thông đã biên tập thận trọng, không gắn nhãn verified fact. Tên Hoover là ví dụ, chưa đối chiếu hình học hay thông số cụ thể. Không dùng con số kỹ thuật thiết kế hoặc tuyên bố công trình tốt nhất.\n\nMốc "kiểm chứng đến 2026-10-02" của tài liệu gốc không được kế thừa như chứng nhận. Tham khảo còn lại trong concept-original.md được giữ nhưng chưa đọc đầy đủ.\n');
const scenes=JSON.parse(fs.readFileSync(`${b}/storyboard.json`,'utf8'));for(const s of scenes){s.sourceIds=entries.filter(e=>e.status==='read'&&e.sentenceIds.includes(s.sentenceIds[0])).map(e=>e.id);s.claimStatus=s.sourceIds.length?'source-linked-partial':'not-independently-verified';}fs.writeFileSync(`${b}/storyboard.json`,JSON.stringify(scenes,null,2)+'\n');
