# -*- coding: utf-8 -*-
"""
Script cập nhật phụ đề song ngữ Tiếng Anh (textEn) cho toàn bộ 227 cụm phụ đề
trong phim tài liệu 'Cuộc Sống Bí Mật Dưới Lòng Đất: Mạng Lưới Nấm'.
Bảo toàn 100% timestamps và từ ngữ tiếng Việt.
Xuất ra src/data/undergroundCaptions.ts.
"""

import json
import re
import sys
from pathlib import Path

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

ENGLISH_TRANSLATIONS = {
    # Part 1 (25 phrases)
    "part1": [
        "An ancient forest on a quiet morning looks perfectly still.",
        "Yet right beneath your feet,",
        "there may be unfolding one of",
        "the most complex communication networks on the planet.",
        "Not fiber-optic cables, not Wi-Fi signals.",
        "What connects these trees lies deep underground,",
        "thinner than human hair, and older than the dinosaurs.",
        "The soil under your feet is actually",
        "one of the most crowded ecosystems on Earth:",
        "worms, bacteria, microscopic insects,",
        "and countless fungal threads,",
        "all bustling together in the dark.",
        "A single teaspoon of healthy forest soil can hold",
        "more living organisms than the total human population.",
        "Scientists gave it a catchy nickname:",
        "the Wood Wide Web, playing on the World Wide Web",
        "that you use every day.",
        "But before diving into that network,",
        "we need to meet the main protagonist,",
        "a bizarre life form",
        "that you rarely see: fungi.",
        "Mycology classifies fungi as their own distinct biological kingdom,",
        "completely separate from plants and animals,",
        "with over 150,000 named species,",
        "and likely millions more waiting to be discovered."
    ],

    # Part 2 (31 phrases)
    "part2": [
        "When hearing 'mushroom', you often picture a small cap",
        "growing on rotting wood or among the grass.",
        "Yet that is merely the 'fruit',",
        "sprouted by fungi to disperse spores,",
        "much like a flower on a tree.",
        "The true body of the fungus is a vast network of fine threads called mycelium,",
        "spreading through the soil in all directions,",
        "sometimes spanning kilometers.",
        "A single meter of healthy forest soil can contain",
        "kilometers of tightly interwoven fungal hyphae,",
        "denser than any power grid humans have ever built.",
        "Fungi are not plants.",
        "They have no green leaves",
        "to make food from sunlight through photosynthesis.",
        "Nor are they animals,",
        "though genetically speaking,",
        "fungi are considered closer to animals than to plants.",
        "Surprising, isn't it?",
        "The scientific term for the symbiosis between fungi",
        "and plant roots, mycorrhiza, was coined by German botanist",
        "Albert Bernhard Frank in 1885,",
        "combining Greek words for 'fungus' and 'root'.",
        "Frank was trying to help farmers cultivate prized truffles.",
        "He had no idea his discovery would unlock an entire",
        "field of scientific study spanning over a century.",
        "Unable to photosynthesize,",
        "fungi must obtain nutrients in another way:",
        "absorbing sustenance from their surroundings,",
        "including from other living organisms.",
        "And their favorite partner of all,",
        "in a remarkably mutualistic partnership, is plant roots."
    ],

    # Part 3 (18 phrases)
    "part3": [
        "About nine out of ten land plant species,",
        "including most forest trees,",
        "live in symbiosis with fungi, known as mycorrhizae.",
        "The trade is remarkably fair.",
        "Trees produce what fungi crave:",
        "sugars, generated by photosynthesis in leafy canopies.",
        "Fungi provide what trees need:",
        "fine threads penetrating microscopic soil pores,",
        "drawing water and minerals like phosphorus,",
        "which coarse tree roots cannot easily reach.",
        "Trees pay sugars to fungi.",
        "Fungi deliver water and minerals to trees.",
        "This fair trade has endured since plants",
        "first colonized dry land,",
        "over four hundred million years ago.",
        "Thanks to this ancient handshake,",
        "scientists believe plants could leave the sea",
        "and survive on early Earth's barren terrestrial soil."
    ],

    # Part 4 (42 phrases)
    "part4": [
        "Fascinatingly, a single fungal hypha rarely serves just one tree.",
        "It connects to the roots of multiple trees simultaneously,",
        "even across completely different species.",
        "This transforms the entire forest,",
        "in essence, into a unified network sharing",
        "a common underground pipeline system.",
        "Canadian ecologist Suzanne Simard was among",
        "the first to measure this scientifically,",
        "back in the 1990s.",
        "She tagged carbon isotopes on one tree,",
        "then tracked whether that carbon showed up in nearby trees,",
        "even though their roots never touched above ground.",
        "The results revealed:",
        "carbon, sugars, and even chemical signals",
        "could travel between trees via this very fungal network.",
        "For the oldest, largest trees,",
        "which possess the widest root networks,",
        "she coined an evocative name: mother trees.",
        "According to her research,",
        "mother trees can recognize their own seedlings growing nearby,",
        "preferentially channeling extra nutrients to them through the shared network.",
        "When an aging tree nears the end of its life,",
        "studies show it may offload most",
        "of its remaining carbon through the network,",
        "like a parting gift",
        "left behind for the forest community.",
        "This poetic concept swiftly captured the public imagination,",
        "featured in countless articles,",
        "documentaries, and even famous blockbuster sci-fi films.",
        "Yet precisely because it was so appealing,",
        "other scientists later urged",
        "a more cautious and critical perspective.",
        "They pointed out that the actual amount of carbon transferred,",
        "in many experiments, is relatively modest,",
        "and may not always yield measurable benefits to recipient trees.",
        "In other words, the underground network is unquestionably real,",
        "but the story of 'mother trees nurturing offspring' might be somewhat romanticized",
        "compared to what current empirical data conclusively proves.",
        "Science continues to investigate,",
        "and that is the beauty of scientific inquiry:",
        "an inspiring hypothesis takes time",
        "to be rigorously tested and confirmed."
    ],

    # Part 5 (46 phrases)
    "part5": [
        "The underground web does not merely transfer sugar and water.",
        "It can also transmit early warning signals.",
        "In controlled experiments,",
        "when a tree is attacked by pests,",
        "it secretes distinct defensive chemical compounds.",
        "Neighboring trees linked to the same mycelial network,",
        "though not yet attacked themselves,",
        "begin producing defensive chemicals preemptively.",
        "It is as if the forest possesses an interconnected alarm system,",
        "with the beleaguered tree calling for help",
        "over the only communication line it has.",
        "Yet this network is not always fair or altruistic.",
        "Opportunists exploit it for selfish gain.",
        "Some peculiar plant species,",
        "devoid of chlorophyll and unable to photosynthesize,",
        "plug their roots directly into the fungal network",
        "to siphon sugar stolen from surrounding trees,",
        "giving nothing back in return.",
        "Warning signals do not just trigger when pests chew on leaves.",
        "A 2010 study found that bean plants",
        "infested by aphids signaled through the fungal network,",
        "causing neighboring plants,",
        "completely untouched by aphids,",
        "to produce aphid-repelling chemicals",
        "while attracting natural predators of aphids.",
        "It resembles plants alerting one another over a secret hotline,",
        "even though no tree can read or write.",
        "A famous example bears a ghost-like name:",
        "the ghost pipe, gleaming pale white on the dark forest floor,",
        "thriving without any need for sunlight.",
        "Within this network, cooperation",
        "and exploitation coexist side by side,",
        "much like any human social network.",
        "There are two primary handshakes between fungi and roots.",
        "Some fungi wrap around root tips like a delicate sheath,",
        "known as ectomycorrhizae,",
        "common in conifers, pines, and oaks.",
        "Others penetrate directly inside root cortical cells,",
        "known as endomycorrhizae,",
        "prevalent in most herbaceous plants",
        "and many agricultural crops.",
        "Two different anatomical partnerships,",
        "sharing the identical biological goal:",
        "expanding the absorption reach",
        "of water and vital minerals,",
        "far beyond what solitary roots could ever achieve alone."
    ],

    # Part 6 (22 phrases)
    "part6": [
        "If you think fungal networks are confined to a few tree roots,",
        "you will think again",
        "when learning about a fungus in Oregon, USA.",
        "Scientists uncovered a single mycelial network,",
        "belonging to one individual organism, spanning underground",
        "across an area equivalent to thousands of football fields.",
        "Researchers did not discover it",
        "by excavating an entire mountain.",
        "Instead, they sampled fungal tissue across distant locations,",
        "compared their genetic profiles,",
        "and realized every sample was an exact DNA match:",
        "one colossal continuous organism.",
        "This individual is estimated to have lived for thousands of years,",
        "quietly expanding inch by inch beneath",
        "the very soil you might be standing on.",
        "It is widely considered a leading contender",
        "for the title of Earth's largest living organism,",
        "by surface area, ever documented on our planet,",
        "far larger than a blue whale.",
        "Yet you will almost never see its massive body,",
        "as virtually all of it resides quietly beneath the earth,",
        "only occasionally pushing up small honey mushrooms in wet autumn."
    ],

    # Part 7 (16 phrases)
    "part7": [
        "Understanding this network is far more than idle curiosity.",
        "It is revolutionizing how humans plant and conserve forests.",
        "When forests are clear-cut",
        "and replanted in rigid industrial monocultures,",
        "the delicate fungal network beneath is pulverized,",
        "leaving young saplings stranded without the underground support",
        "that natural forests instinctively provide.",
        "Modern reforestation projects deliberately preserve",
        "mature legacy trees as network hubs,",
        "giving newly planted saplings immediate underground anchorage.",
        "Fungal networks also lock massive amounts of carbon deep in the soil,",
        "forming a crucial puzzle piece in combating climate change.",
        "In essence, when you protect an ancient forest,",
        "you are safeguarding not just the trees you see,",
        "but an entire living underground infrastructure,",
        "vast, silent, and vital beneath our feet."
    ],

    # Part 8 (27 phrases)
    "part8": [
        "Next time you take a stroll through the woods,",
        "you may be walking over thousands of miles of living wires",
        "without even realizing it,",
        "thinner than hair, older than dinosaurs,",
        "and quieter than any communication grid humanity ever conceived.",
        "Recently, scientists have even measured",
        "tiny electrical impulses traveling along fungal hyphae,",
        "shifting rhythms depending on environmental conditions.",
        "Some liken it to a rudimentary biological language,",
        "though this remains a debated frontier",
        "requiring much more empirical confirmation.",
        "The popular phrase 'Wood Wide Web'",
        "was actually not coined by scientists.",
        "It first appeared on the cover of a renowned scientific journal",
        "back in 1997,",
        "swiftly becoming a beloved household metaphor",
        "far more famous with the public than within academic circles.",
        "This living web is not confined to remote forests.",
        "In grasslands, agricultural fields,",
        "and even your own backyard,",
        "similar fungal threads work silently beneath your feet,",
        "even if they receive less attention than grand ancient groves.",
        "Pioneering regenerative farmers now heed this wisdom,",
        "shifting toward low-till and no-till farming",
        "to avoid shattering this invaluable fungal web each planting season.",
        "Thank you for watching.",
        "See you next time."
    ]
}

def main():
    captions_file = Path("src/data/undergroundCaptions.ts")
    content = captions_file.read_text(encoding="utf-8")

    # Extract JSON part
    prefix = 'export const UNDERGROUND_CAPTIONS: Record<string, CaptionPhrase[]> = '
    parts = content.split(prefix)
    json_text = parts[1].strip().rstrip(";").strip()
    json_text = re.sub(r",\s*\}", "}", json_text)
    data = json.loads(json_text)

    total_translated = 0
    for sec_id, phrases in data.items():
        en_list = ENGLISH_TRANSLATIONS.get(sec_id, [])
        if len(en_list) != len(phrases):
            print(f"⚠️ Cảnh báo: {sec_id} có {len(phrases)} phrases nhưng có {len(en_list)} bản dịch En.")
        for idx, p in enumerate(phrases):
            if idx < len(en_list):
                p["textEn"] = en_list[idx]
                total_translated += 1

    # Format TypeScript file
    out_lines = [
        '// Auto-generated bilingual subtitles (VN + EN) for UndergroundDocumentary',
        'import type { CaptionPhrase } from "./historyGapsCaptions";\n',
        'export const UNDERGROUND_CAPTIONS: Record<string, CaptionPhrase[]> = {'
    ]

    for sec_id, phrases in data.items():
        out_lines.append(f'  "{sec_id}": {json.dumps(phrases, ensure_ascii=False, indent=4)},')

    out_lines.append('};\n')

    captions_file.write_text("\n".join(out_lines), encoding="utf-8")
    print(f"🎉 Đã thêm phụ đề tiếng Anh cho toàn bộ {total_translated} cụm phụ đề vào {captions_file}!")

if __name__ == "__main__":
    main()
