# -*- coding: utf-8 -*-
"""
Perfect 1-to-1 alignment for Pharaoh (387 phrases).
"""
import json
from pathlib import Path

# Load extracted VN phrases
d_vn = json.loads(Path("src/data/pharaoh_phrases_for_en.json").read_text(encoding="utf-8"))

PHARAOH_PERFECT_EN = {
    "part1": [
        "When thinking of ancient Egypt,",
        "almost everyone immediately pictures a single image:",
        "colossal pyramids towering over the desert,",
        "the final resting places of the pharaohs.",
        "Yet there is a fact very few people notice:",
        "pyramids were built only during a relatively short window of ancient Egyptian history—",
        "about one thousand two hundred years,",
        "from King Djoser to King Ahmose the First.",
        "After that, for nearly a thousand years to follow,",
        "not a single pharaoh ever built another royal pyramid.",
        "Instead, they chose an entirely different way to prepare for death:",
        "carving deep tombs into the rocky mountains,",
        "hidden away in a secluded valley,",
        "leaving no surface trace that a king was resting beneath.",
        "Today, that valley is known as the Valley of the Kings.",
        "But the story doesn't end there.",
        "At the very moment pharaohs were concealing their final resting place,",
        "they poured an enormous fortune into building an entirely different monument—",
        "public, lavish, and growing more colossal through each dynasty—",
        "namely Karnak Temple, the largest religious complex ever built by human hands.",
        "Why this striking contradiction?",
        "Why did the Egyptians want both secrecy",
        "and flamboyant display at the exact same time?",
        "The answer, as we shall uncover,",
        "was not merely a matter of security,",
        "but tied to economics,",
        "religion, and a profound shift in mindset regarding death and absolute power."
    ],

    "part2": [
        "Before discovering why the pyramids were abandoned,",
        "we must first understand why they were ever built in the first place.",
        "Egypt's first pyramid was built about four thousand seven hundred years ago",
        "under the reign of King Djoser.",
        "Originally, this was just a flat, rectangular structure",
        "known as a mastaba—Arabic for 'bench'.",
        "However, Djoser's royal architect,",
        "a real historical figure named Imhotep,",
        "who was later revered as the first architect in Egyptian history to build with stone,",
        "conceived a groundbreaking breakthrough:",
        "stacking progressively smaller mastabas on top of one another,",
        "forming a monumental stepped shape.",
        "That was the Step Pyramid at Saqqara,",
        "the first large-scale stone monument in human history.",
        "From then on, across generations of pharaohs,",
        "the pyramid shape was gradually perfected,",
        "evolving from steps into the smooth, true pyramids we know today,",
        "culminating in the magnificent Giza pyramid complex,",
        "built about four thousand five hundred years ago.",
        "To the Egyptians of the Old Kingdom,",
        "a pyramid was far more than a simple tomb.",
        "It was the ultimate symbol of the pharaoh's supreme authority,",
        "revered as the living embodiment of the divine on Earth.",
        "The pyramid's sharp apex reaching straight toward the heavens was believed to represent",
        "the sun's descending rays,",
        "allowing the departed pharaoh's soul to ascend straight into the sky to unite with the Sun God.",
        "Yet building such mammoth monuments demanded staggering resources:",
        "tens of thousands of laborers, decades of construction,",
        "and immense blocks of stone hauled from quarries hundreds of kilometers away.",
        "This scale of construction could only be sustained during a golden era of peak Egyptian prosperity",
        "and political stability.",
        "And that became the very turning point of our story."
    ],

    "part3": [
        "There was a painful paradox that Egyptian pharaohs and priests gradually",
        "realized over the centuries:",
        "the sheer grandeur and scale of the pyramid,",
        "originally built to glorify royal power,",
        "became its very fatal flaw.",
        "A monument hundreds of meters tall,",
        "looming against the desert skyline and visible from dozens of kilometers away,",
        "was effectively a giant billboard proclaiming to the entire world:",
        "'Vast treasures of gold and gems lie buried within!'",
        "Inside each pyramid, alongside the mummified remains of the pharaoh,",
        "the ancient Egyptians interred a massive fortune:",
        "gold, fine jewelry, precious furniture,",
        "food, and countless items they believed the pharaoh would need in the afterlife.",
        "To grave robbers,",
        "this was an irresistible treasure trove.",
        "And in reality, almost all Egyptian pyramids,",
        "despite being engineered with secret corridors,",
        "decoy false doors, and crushing stone traps,",
        "were ultimately located and plundered by tomb raiders,",
        "mostly in ancient times—",
        "some robbed merely a few generations after completion.",
        "There is a particularly striking detail:",
        "earlier mastaba tombs,",
        "built from mud-brick rather than stone,",
        "were even more vulnerable to intrusion;",
        "thieves needed only to tunnel straight down from above",
        "to breach the riches inside.",
        "By the late Old Kingdom and especially through the Middle Kingdom,",
        "grave robbery escalated to an alarming epidemic.",
        "Pharaohs and the priesthood came to realize",
        "that colossal size and grandeur did not guarantee safety.",
        "On the contrary, it only painted a brighter target on the tomb."
    ],

    "part4": [
        "Beyond the issue of security,",
        "another pragmatic factor played an equally crucial role:",
        "the cost of building pyramids",
        "became increasingly expensive and unsustainable over the centuries.",
        "Constructing monuments rivaling or surpassing the giant pyramids",
        "of the Fourth Dynasty,",
        "such as the Great Pyramid of Giza, demanded economic and human resources",
        "on a scale virtually impossible to sustain over successive generations.",
        "Many researchers argue that",
        "economically, continuing to erect ever-larger pyramids,",
        "or even maintaining equivalent scale,",
        "had become prohibitively costly,",
        "forcing subsequent dynasties to seek a new direction for royal burials.",
        "This brings us to a pivotal concept",
        "that resolves the mystery completely:",
        "the deliberate separation between burial place and place of worship."
    ],

    "part5": [
        "In the Old Kingdom,",
        "burial and worship were unified into a single monument complex:",
        "the pharaoh's body was interred deep inside the pyramid,",
        "while adjoining mortuary temples right next to it handled rituals.",
        "This meant an intruder who found the temple had already found the tomb.",
        "Realizing this deadly vulnerability,",
        "pharaohs of the New Kingdom pioneered a revolutionary strategic change:",
        "permanently separating the two functions.",
        "The physical body of the pharaoh, along with priceless burial treasures,",
        "would be concealed deep in hidden underground chambers,",
        "guarded in total secrecy in an isolated mountain valley.",
        "No monumental markers, no statues, no clues.",
        "Meanwhile, public rituals,",
        "honoring the divine legacy of departed kings,",
        "would be hosted in completely separate temples—",
        "magnificently built out in the open,",
        "continually expanded over successive reigns,",
        "right within the bustling populated districts",
        "of Egypt's new capital at the time:",
        "Thebes, known today as the modern city of Luxor.",
        "In other words, the Egyptians devised a way to maintain the grand spectacle",
        "necessary to project the pharaoh's divine kingship,",
        "while securing absolute safety for their physical remains and true treasures.",
        "A hidden tomb safeguarded the body;",
        "a public temple perpetuated the cult.",
        "No pyramid was ever needed again.",
        "And this very idea gave birth to two of history's greatest landmarks",
        "that we will explore in detail:",
        "the Valley of the Kings and Karnak Temple.",
        "A magnificent duel between shadow and light.",
        "A legacy carved into stone forever."
    ],

    "part6": [
        "The Valley of the Kings lies on the west bank of the Nile,",
        "directly opposite ancient Thebes,",
        "nestled amid the barren limestone cliffs of the desert.",
        "There is a fascinating geographic detail that many scholars believe",
        "influenced the choice of this site:",
        "directly above the valley stands a natural peak named el-Qurn,",
        "possessing the exact natural silhouette of a pyramid.",
        "In other words, New Kingdom pharaohs still possessed the sacred pyramid symbol",
        "resting right above their final sleep,",
        "except this time, it was sculpted by mother nature herself,",
        "not built by human hands,",
        "and thus presented no obvious lure to tomb raiders.",
        "The first pharaoh believed to have chosen burial in the Valley of the Kings",
        "instead of a pyramid",
        "was Thutmose the First, who reigned around the 16th century BC—",
        "though some Egyptologists still argue his predecessor,",
        "Amenhotep the First, may have been the true pioneer.",
        "Interestingly, unlike pyramids,",
        "where entrances were signaled by the monument's exterior,",
        "tombs in the Valley of the Kings were hewn deep into solid limestone bedrock,",
        "with meticulously camouflaged entrances,",
        "often intentionally buried under rubble and construction debris",
        "from subsequent tombs excavated higher on the hillside.",
        "The valley was further guarded by an elite necropolis security force,",
        "stationed around the clock to intercept any intruders.",
        "Yet even with all these sophisticated safeguards,",
        "modern Egyptologists remain intrigued by the full array of motivations",
        "that led to choosing the Valley of the Kings for royal burials.",
        "It was most likely a combination of several converging factors:",
        "superior security provided by remote and treacherous terrain;",
        "a major shift in theological thought,",
        "as the king's nocturnal passage through the underworld became",
        "central to New Kingdom religion,",
        "demanding intricate tomb layouts carved deep subterranean chambers",
        "that mirrored that very journey;",
        "and the practical topography of Thebes itself,",
        "which served as Egypt's new capital during this golden age,",
        "lacking the broad, flat expanses",
        "required to erect colossal pyramids like those built at Giza centuries earlier."
    ],

    "part7": [
        "Constructing these secret,",
        "sophisticated tombs required a permanent cadre of master artisans,",
        "working over long periods under sworn oaths of absolute secrecy.",
        "To achieve this, the Egyptian state built a dedicated village exclusively for these craftsmen,",
        "named Deir el-Medina, located near the Valley of the Kings.",
        "This was essentially a self-contained, gated community,",
        "fully supplied by the state with rations and everyday necessities.",
        "In return, the villagers dedicated their entire lives,",
        "across successive generations,",
        "to quarrying, painting, and perfecting the royal tombs in the nearby valley.",
        "Yet in an ironic twist of historical fate,",
        "full of profound irony,",
        "the very craftsmen who knew the interior layouts intimately,",
        "the exact hiding spots of golden treasures,",
        "and the precise hour a tomb was officially sealed,",
        "were uniquely positioned to become,",
        "or collude with, the tomb raiders of subsequent eras."
    ],

    "part8": [
        "In a striking turn of history,",
        "despite far superior concealment compared to the pyramids,",
        "most tombs in the Valley of the Kings eventually suffered the same fate of plunder.",
        "The clearest historical documentation of tomb robberies during this era comes from",
        "a remarkable cache of ancient legal documents,",
        "collectively known as the Mayer B papyrus,",
        "which detail trials of apprehended grave robbers",
        "held in Thebes during the Twentieth Dynasty,",
        "around the 12th to 11th centuries BC.",
        "These records show that the first wave of large-scale looting erupted",
        "toward the twilight of the Twentieth Dynasty,",
        "perpetrated by local robber gangs",
        "that notoriously included craftsmen and officials who had directly built",
        "or administered those very tombs.",
        "Then, during the Twenty-First Dynasty,",
        "a second wave of looting unfolded—",
        "this time orchestrated by officials under the High Priests of Amun themselves,",
        "the most powerful clergy at Karnak Temple,",
        "which we will examine shortly.",
        "In other words, the very guardians entrusted with protecting royal sanctity",
        "were sometimes the ones enabling its plunder.",
        "Faced with this systemic crisis in later eras,",
        "the Egyptian priesthood undertook a dramatic operation:",
        "secretly evacuating mummies of celebrated pharaohs from their compromised tombs,",
        "which had been ransacked or faced imminent threat,",
        "and consolidating them into one or two secure, camouflaged hiding spots",
        "known today by archaeologists as royal mummy caches.",
        "This explains why many famous pharaoh mummies uncovered by archaeologists",
        "were never found in the original tombs built for them."
    ],

    "part9": [
        "Amidst a landscape where nearly every royal tomb had been violated",
        "over thousands of tumultuous years,",
        "there was one miraculous exception:",
        "the tomb of the young boy pharaoh, Tutankhamun.",
        "Tutankhamun was a relatively minor ruler,",
        "dying at a very tender age,",
        "and virtually erased from the official king lists of ancient Egypt.",
        "His tomb was significantly more modest than those of reigning titans,",
        "likely originally intended for another royal courtier",
        "before being hastily adapted to inter Tutankhamun",
        "due to his sudden and unexpected death.",
        "Yet it was precisely this modest footprint,",
        "situated low on the valley floor,",
        "that caused the entrance to Tutankhamun's tomb",
        "over time to be completely smothered",
        "under limestone gravel and construction debris from other tombs excavated directly above.",
        "The tomb had actually been breached twice",
        "shortly after the royal funeral,",
        "but both intrusions were caught swiftly,",
        "and necropolis officials resealed the entrance securely.",
        "Then, thanks to that providential blanket of debris,",
        "the tomb vanished entirely from the sight of plunderers for over three millennia.",
        "Until 1922, when British archaeologist Howard Carter,",
        "after years of relentless searching,",
        "finally uncovered the virtually intact burial chamber,",
        "igniting one of the greatest archaeological sensations in human history.",
        "Not because Tutankhamun was an exceptionally monumental ruler,",
        "but because his was virtually the only royal tomb to survive with its original treasures intact,",
        "preserving the grave goods virtually undisturbed,",
        "offering the world a singular, breathtaking glimpse",
        "into the unbridled wealth an Egyptian pharaoh possessed before the thieves struck."
    ],

    "part10": [
        "While the true resting places of pharaohs were tucked away in secrecy,",
        "just across the river on the east bank of the Nile,",
        "an entirely opposite monument was continuously expanding",
        "across generations: Karnak Temple.",
        "Ancient Egyptians named this sanctuary Ipet-Isut,",
        "meaning 'The Most Select of Places'.",
        "Karnak was consecrated to the supreme patron deity of New Kingdom Egypt:",
        "Amun-Ra,",
        "the magnificent synthesis of Thebes' local god Amun with the sun deity Ra,",
        "revered throughout the entire realm.",
        "The earliest archaeological traces of a shrine at Karnak date back to",
        "King Intef the Second around 2100 BC—",
        "originally just a modest shrine,",
        "built from sun-dried mud bricks.",
        "However, once the Eighteenth Dynasty ascended,",
        "igniting the glorious New Kingdom era around 1550 BC,",
        "Thebes emerged as the glittering epicentre of power and treasure for all Egypt,",
        "and Karnak began expanding at a dizzying pace.",
        "For nearly two thousand consecutive years thereafter,",
        "over thirty different pharaohs contributed to constructing,",
        "expanding, and embellishing the grand temple complex,",
        "transforming it into the largest religious edifice ever built by human hands."
    ],

    "part11": [
        "To truly grasp the monumental scale of Karnak,",
        "perhaps nothing compares better than measuring it against iconic landmarks",
        "we are familiar with today.",
        "The core sacred precinct of Karnak,",
        "dedicated exclusively to Amun-Ra, spans sixty-one acres—",
        "spacious enough to comfortably hold ten grand European cathedrals at once.",
        "Across the entire expanded complex,",
        "Karnak sprawled over approximately two hundred forty-seven acres,",
        "occupying at its zenith an area roughly equivalent to nearly half",
        "the size of Manhattan Island in New York City.",
        "This was far more than a temple in the ordinary sense;",
        "Karnak operated virtually as a self-sustaining miniature city,",
        "complete with administrative bureaus,",
        "palaces, treasuries, bakeries,",
        "breweries, granaries,",
        "and even its own dedicated scribal school.",
        "One of Karnak's crowning achievements is the Great Hypostyle Hall,",
        "commissioned around 1375 BC.",
        "This is an awe-inspiring stone forest of one hundred thirty-four soaring columns,",
        "intricately carved and vibrantly adorned—",
        "so vast that placed side-by-side,",
        "both Notre-Dame of Paris and Saint Peter's in Rome could nestle inside.",
        "Karnak was also renowned for towering monolithic stone spires,",
        "known as obelisks.",
        "The largest surviving obelisk standing at Karnak reaches nearly thirty meters in height",
        "and weighs around three hundred twenty-three tons—",
        "equivalent to the weight of a Boeing 747 airliner.",
        "And unlike pyramids, which were built by a single pharaoh",
        "within a single reign,",
        "Karnak was an ever-evolving project built continuously by dozens of monarchs",
        "over nearly two millennia of uninterrupted history.",
        "Each ascending pharaoh",
        "regarded expanding and enriching",
        "this grand temple as the ultimate proof of royal legitimacy",
        "and devotion to the god Amun-Ra,",
        "as well as a monumental canvas to etch their dynasty's power into eternity."
    ],

    "part12": [
        "A natural question arises:",
        "with such colossal scale,",
        "built and expanded continuously for almost two thousand years,",
        "what tremendous wealth financed this entire endeavor?",
        "The answer lies in the shifting nature of Egyptian imperial power",
        "entering the New Kingdom.",
        "This was an era when Egypt,",
        "commanded by pharaohs of extraordinary military prowess,",
        "dramatically expanded its sphere of dominance far beyond traditional frontiers,",
        "launching massive campaigns into the Near East and Nubia to the south.",
        "Karnak was financed primarily by imperial tax revenues collected across the realm,",
        "combined with astronomical quantities of war plunder brought home by pharaohs",
        "from triumphant military expeditions.",
        "Whenever Egypt secured a major military victory,",
        "a lavish portion of the spoils was dedicated to expanding",
        "and embellishing the temple of Amun-Ra,",
        "the patron deity they believed had blessed them with triumph,",
        "ensuring victory in battle.",
        "This formed an extraordinary self-reinforcing cycle of power:",
        "military conquests yielded immense treasure;",
        "treasure was poured into monumental temples;",
        "and temples fortified the pharaoh's divine mandate,",
        "empowering the throne to mobilize armies for the next campaign."
    ],

    "part13": [
        "Yet Karnak's immense fortune and absolute religious dominance",
        "gradually fostered a consequence the pharaohs never anticipated:",
        "the rise of a rival political force",
        "capable of directly challenging royal authority—",
        "the priesthood of Amun at Karnak.",
        "Over generations of amassing riches,",
        "vast agricultural lands, and temple laborers,",
        "the High Priests of Amun at Karnak grew exceedingly affluent and influential,",
        "to the point where in later dynasties,",
        "their authority openly rivaled,",
        "and sometimes overshadowed, the political power of the sitting pharaoh.",
        "This was a key driver behind Pharaoh Akhenaten's radical actions—",
        "the king famous for the most contentious religious revolution in Egyptian history—",
        "who severed ties with Amun and the entrenched priesthood at Karnak,",
        "founding an open-air temple to the sun disc Aten",
        "situated strategically right beside Karnak to capture the morning sun",
        "before its rays could strike the temple of Amun.",
        "This was the only brief pause in nearly two thousand years of Karnak's growth,",
        "when expansion was abruptly suspended,",
        "a vivid testament that behind its divine facade,",
        "Karnak was deeply entwined with the ruthless politics of power",
        "between the pharaoh and the priestly elite,",
        "vying for total control of the state."
    ],

    "part14": [
        "Looking back across the sweeping story,",
        "we see that the Valley of the Kings and Karnak Temple,",
        "despite appearing polar opposites—",
        "one shrouded in hidden silence,",
        "the other blazing with monumental grandeur—",
        "were actually two complementary halves of a singular solution devised by the New Kingdom",
        "to solve the dilemma that had vexed pharaohs for over a thousand years.",
        "The pyramid, though a magnificent symbol of majesty,",
        "was burdened with two mutually contradictory missions:",
        "it had to be publicly colossal to proclaim divine kingship,",
        "yet impenetrable enough to protect the king's mummy and golden hoard.",
        "Through centuries of painful plunder,",
        "the Egyptians discovered that no single monument could fulfill both roles simultaneously.",
        "So they severed the two functions forever.",
        "Absolute secrecy and security were entrusted to hidden rock-cut tombs",
        "deep in the arid mountains of the Valley of the Kings.",
        "Meanwhile, spectacle and imperial grandeur,",
        "embodying the wealth and power of an entire civilization,",
        "were channeled into Karnak Temple—",
        "a sanctuary continually magnified over two millennia",
        "by dozens of successive pharaohs,",
        "becoming the most colossal religious monument humanity had ever raised.",
        "That is the answer not merely to why pharaohs stopped building pyramids,",
        "but how a civilization learned to balance the impulse to display power",
        "with the imperative to safeguard its most sacred treasures from human greed—",
        "a timeless lesson that echoes through history,",
        "that resonated far beyond ancient Egypt,",
        "reminding us of the eternal conflict between vanity and survival,",
        "and the delicate balance every civilization must find."
    ]
}

# Verify counts match 100%
total_expected = sum(len(v) for v in d_vn.values())
total_actual = sum(len(v) for v in PHARAOH_PERFECT_EN.values())
print(f"Total VN: {total_expected}, Total EN: {total_actual}")

for sec in d_vn:
    l_vn = len(d_vn[sec])
    l_en = len(PHARAOH_PERFECT_EN.get(sec, []))
    assert l_vn == l_en, f"Mismatch in {sec}: {l_vn} vs {l_en}"

Path("src/data/pharaoh_translations_en.json").write_text(
    json.dumps(PHARAOH_PERFECT_EN, ensure_ascii=False, indent=2), encoding="utf-8"
)
print("✅ Verified: 100% matching length for all 14 chapters of Pharaoh!")
