# -*- coding: utf-8 -*-
"""
Mô tả chi tiết 170 phân cảnh bằng tiếng Việt cho phim tài liệu
'TOÀN CẢNH KHỦNG LONG: HÀNH TRÌNH QUA CÁC NHÓM LOÀI THỐNG TRỊ TRÁI ĐẤT'
"""

DINOSAUR_DESCRIPTIONS = [
    # PHẦN 1 — MỞ BÀI: LÀM RÕ HIỂU LẦM (001 - 010)
    "Toàn cảnh kỷ Trung sinh: Ba nhóm sinh vật riêng biệt trên không, dưới biển và trên cạn",
    "Thằn lằn bay Pteranodon sải cánh chao lượn trên vách đá ven biển",
    "Thương long Mosasaurus khổng lồ - Quái vật săn mồi thống trị đại dương sâu thẳm",
    "Thằn lằn cổ dài Plesiosaurus bơi lội uyển chuyển dưới làn nước trong xanh",
    "Sơ đồ so sánh giải phẫu: Khớp hông đứng thẳng của khủng long đối lập chân bò sát",
    "Hệ sinh thái tiền sử rộng lớn với bầy khủng long trên bờ và sinh vật biển dưới nước",
    "Cây phả hệ ba nhánh phát sáng: Khủng long trên cạn, thằn lằn bay và bò sát biển",
    "Bình minh sương mù trên rừng dương xỉ nguyên sinh kỷ Trung sinh",
    "Đối chiếu kích thước: Con người nhỏ bé trước hóa thạch xương chân khủng long khổng lồ",
    "Bình minh kỳ vĩ trên đại ngàn kỷ Trung sinh với núi lửa hoạt động phía chân trời",

    # PHẦN 2 — HAI NHÁNH CHÍNH (011 - 016)
    "Sơ đồ phân nhánh tiến hóa: Hai nhóm Saurischia (hông thằn lằn) và Ornithischia (hông chim)",
    "Bản vẽ giải phẫu so sánh cấu trúc xương hông giữa hai nhánh khủng long chính",
    "Biểu tượng phân nhóm: Khủng long ăn thịt Theropod, cổ dài Sauropod và khủng long mang sừng",
    "Nghịch lý tiến hóa: Loài chim hiện đại tiến hóa từ nhánh Theropod thuộc nhóm hông thằn lằn",
    "Bản thảo nghiên cứu cổ sinh vật học phác họa chi tiết cấu trúc giải phẫu xương hông",
    "Cây sự sống tiền sử tỏa sáng rực rỡ với các nhánh khủng long phân hóa đa dạng",

    # PHẦN 3 — NHÓM THEROPODA: KẺ SĂN MỒI HAI CHÂN (017 - 040)
    "Bạo chúa Tyrannosaurus rex sừng sững giữa khu rừng cổ đại đầy uy lực",
    "Cận cảnh đầu T-rex với hàm răng sắc nhọn và ánh mắt săn mồi sắc lạnh",
    "Tiếng gầm xé toang bầu trời của T-rex giữa khung cảnh bão tố tiền sử",
    "Đàn Velociraptor có lông vũ rình rập phối hợp săn mồi trong bãi cỏ rậm rạp",
    "Cận cảnh đầu và vuốt lưỡi liềm sắc lẹm ở ngón chân thứ hai của Velociraptor",
    "Khủng long ăn thịt Spinosaurus lội qua sông săn cá với cánh buồm lớn trên lưng",
    "Cận cảnh mõm dài dạng cá sấu của Spinosaurus ngoạm chặt con cá lớn dưới nước",
    "Đàn Ornithomimidae hình dáng giống đà điểu lao nhanh trên đồng bằng tiền sử",
    "Khủng long kỳ dị Therizinosaurus với bộ móng vuốt hình lưỡi hái dài ngoạn mục",
    "Cận cảnh móng vuốt khổng lồ dài hơn nửa mét của Therizinosaurus so với tay người",
    "Dị long Allosaurus rình mồi trong rừng kỷ Jura với gờ xương đặc trưng trên mắt",
    "Khủng long tí hon có lông Compsognathus nhanh nhẹn đuổi bắt thằn lằn nhỏ",
    "Carnotaurus với hai chiếc sừng bò hung dữ lao nhanh trên vùng đất quang đãng",
    "Giganotosaurus - Kẻ săn mồi khổng lồ phương nam đứng bên bờ sông buổi hoàng hôn",
    "Cuộc đối đầu căng thẳng ngộp thở giữa bạo chúa T-rex và Triceratops ba sừng",
    "T-rex non với lớp lông tơ mềm mại, cơ thể thon gọn và vô cùng nhanh nhẹn",
    "Biểu đồ so sánh kích thước giữa T-rex, Spinosaurus, Giganotosaurus và con người",
    "Bầy Deinonychus phục kích phối hợp quật ngã khủng long ăn cỏ to lớn",
    "Sơ đồ cấu trúc rỗng đặc trưng bên trong xương của nhóm Theropoda",
    "Yutyrannus phủ lớp lông vũ dày xù xì sinh sống giữa cảnh quan tuyết trắng cổ đại",
    "Dấu chân khổng lồ sâu hoắm của T-rex đọng nước mưa trên nền đất bùn cổ xưa",
    "Toàn cảnh các loài Theropoda cùng tụ họp săn mồi bên bờ nước lúc chạng vạng",
    "Cận cảnh những chiếc răng cưa sắc nhọn như dao găm của khủng long ăn thịt",
    "Bóng dáng uy nghi của T-rex bước đi trong sương mù bình minh mờ ảo",

    # PHẦN 4 — NHÓM SAUROPODOMORPHA: GÃ KHỔNG LỒ CỔ DÀI (041 - 060)
    "Brachiosaurus vươn chiếc cổ khổng lồ thẳng đứng hái lá trên ngọn cây cao vút",
    "Bầy Brachiosaurus di chuyển tạo nên cảnh tượng đồ sộ trên thảo nguyên tiền sử",
    "Cận cảnh đầu nhỏ gọn của Brachiosaurus với lỗ mũi đặt cao trên đỉnh sọ",
    "Gã khổng lồ kỷ lục Argentinosaurus với kích thước áp đảo toàn bộ cây cối xung quanh",
    "Hình ảnh đối chiếu quy mô: Argentinosaurus tương đương trọng lượng mười chiếc xe buýt",
    "Diplodocus với chiếc đuôi dài như roi da bước đi bên bờ sông rực rỡ hoàng hôn",
    "Tổ tiên nguyên thủy nhỏ bé của nhóm cổ dài di chuyển bằng hai chân vào kỷ Tam Điệp",
    "Khủng long cổ dài non nớt vừa cắn vỡ vỏ trứng chui ra tại khu tổ ấp",
    "Bãi làm tổ khổng lồ với hàng chục hố trứng tròn xếp theo hình vòng cung",
    "Brontosaurus lội qua đầm nước nông, từng bước chân tạo sóng nước lan tỏa",
    "Cận cảnh cấu trúc chân cột trụ khổng lồ giúp nâng đỡ trọng lượng cơ thể chục tấn",
    "Chiếc cổ uốn lượn tuyệt đẹp của Brachiosaurus vươn qua khúc sông đón ráng chiều",
    "Gia đình Titanosaurus gồm cá thể trưởng thành và con non lững thững trong sương rừng",
    "Sơ đồ mô phỏng hệ tiêu hóa lên men khổng lồ tiêu thụ hàng trăm ký lá mỗi ngày",
    "Bộ xương Sauropod sừng sững cao vút chạm trần trong đại sảnh bảo tàng",
    "Khủng long ăn thịt nhỏ bé lượn lờ nhặt nhạnh thức ăn quanh chân bầy Sauropod",
    "Bóng dáng thanh thoát của khủng long cổ dài in bóng trên nền trời hoàng hôn rực cam",
    "Dấu chân khổng lồ hằn sâu thành chuỗi dài trên nền bùn cổ đại nhìn từ trên cao",
    "Khoảnh khắc ấm áp: Chú khủng long non bé nhỏ nép mình bên chân mẹ khổng lồ",
    "Đoàn di cư tráng lệ của bầy khủng long cổ dài băng qua đồng lũ lúc bình minh",

    # PHẦN 5 — NHÓM STEGOSAURIA: TẤM GIÁP LƯNG BÍ ẨN (061 - 072)
    "Stegosaurus kiêu hãnh với hàng giáp xương nhô cao đón ánh nắng kỷ Jura",
    "Cận cảnh bề mặt tấm giáp xương với những rãnh mạch máu điều hòa thân nhiệt",
    "Stegosaurus quất mạnh chiếc đuôi bốn gai nhọn Thagomizer để tự vệ trước kẻ thù",
    "Cận cảnh bốn chiếc gai xương sắc nhọn nguy hiểm ở chóp đuôi Thagomizer",
    "Stegosaurus gặm dương xỉ thấp với hộp sọ nhỏ bé tương phản thân hình hộ pháp",
    "Hai cá thể Stegosaurus phô diễn các phiến giáp ửng sắc để giao tiếp hoặc tán tỉnh",
    "Dáng hình răng cưa đặc trưng của Stegosaurus in đậm trên sống núi hoàng hôn",
    "Họ hàng gai nhọn Kentrosaurus với hàng gai sắc bén trên lưng tại châu Phi cổ đại",
    "Sơ đồ so sánh hai giả thuyết: Chức năng điều hòa nhiệt độ đối lập phô diễn hình thể",
    "Tình mẫu tử tiền sử: Stegosaurus mẹ dịu dàng che chở cho con non mới lớn",
    "Bầy Stegosaurus bình yên gặm cỏ giữa rừng cây mè vảy cycad đặc trưng kỷ Jura",
    "Hóa thạch phiến giáp và gai đuôi Stegosaurus được bảo tồn nguyên vẹn trong tầng đá",

    # PHẦN 6 — NHÓM ANKYLOSAURIA: XE TĂNG SỐNG TIỀN SỬ (073 - 084)
    "Chiến xa bọc giáp Ankylosaurus vững chãi với lớp vảy xương bao phủ toàn thân",
    "Cận cảnh chùy đuôi bằng khối xương đặc cứng như đá hoa cương sẵn sàng giáng đòn",
    "Cú quất đuôi sấm sét của Ankylosaurus đập gãy xương chân kẻ săn mồi hung hãn",
    "Cận cảnh phần đầu bọc thép kiên cố, thậm chí mí mắt cũng có xương bảo vệ",
    "Góc máy từ dưới lên khắc họa hình bóng bọc thép kiên cố như pháo đài di động",
    "Ankylosaurus thong dong gặm cỏ bụi, hoàn toàn miễn nhiễm trước kẻ săn mồi nhỏ",
    "Họ hàng gần Euoplocephalus với hoa văn giáp xương độc đáo đi xuyên qua bụi rậm",
    "Mặt cắt giải phẫu lớp giáp xương Osteoderm gắn chặt vào mô da bảo vệ toàn thân",
    "Kẻ săn mồi nản lòng thoái lui trước bộ giáp phòng thủ bất khả xâm phạm",
    "Khủng long giáp non với lớp giáp mềm đang phát triển luôn đi sát cạnh con trưởng thành",
    "Đàn xe tăng sống lầm lũi tiến bước qua vùng bình nguyên khô cằn mù mịt bụi",
    "Hóa thạch Ankylosaurus hóa đá hoàn mỹ với nguyên vẹn áo giáp sắt triệu năm",

    # PHẦN 7 — NHÓM CERATOPSIA: CHIẾN BINH MANG SỪNG (085 - 100)
    "Chiến binh Triceratops sừng sững uy nghi với ba sừng nhọn và diềm cổ khổng lồ",
    "Cận cảnh đầu Triceratops với hai sừng mày dài nhọn hoắt và diềm xương gồ ghề",
    "Hai con đực Triceratops khóa sừng quyết liệt trong trận đấu giành bạn tình",
    "Triceratops hạ thấp đầu chĩa sừng nghênh chiến trực diện bạo chúa T-rex",
    "Khủng long mặt sừng nguyên thủy Protoceratops cỡ con cừu trên vùng bán hoang mạc",
    "Styracosaurus với diềm cổ mang vô số gai xương dài tủa ra như vương miện lộng lẫy",
    "Cận cảnh những chiếc gai nhọn hoắt trên diềm cổ Styracosaurus rực sáng dưới nắng",
    "Bầy đàn Triceratops đông đảo gặm cỏ cùng nhau thể hiện tập tính xã hội cao",
    "Triceratops mẹ dũng cảm che chắn bảo vệ con non trước kẻ rình mồi trong cỏ",
    "Hộp sọ hóa thạch Triceratops mang vết sẹo lành xương từ những cuộc giao đấu",
    "Pentaceratops với khuôn mặt năm sừng kỳ vĩ và diềm cổ cao đồ sộ nhất họ sừng",
    "Bóng hình chiếc đầu ba sừng trứ danh của Triceratops in bóng trên nền trời đỏ rực",
    "Triceratops con ngây thơ tò mò khám phá thế giới với diềm cổ đang dần hình thành",
    "Sơ đồ giải phẫu so sánh đa dạng kiểu dáng sừng và diềm cổ của các loài Ceratopsia",
    "Cả bầy Triceratops đắm mình tắm bùn thư giãn tại đầm nước mát lành",
    "Đội hình phòng thủ vòng tròn kiên cố của bầy Triceratops bảo vệ đàn con non",

    # PHẦN 8 — NHÓM ORNITHOPODA: LOÀI ĂN CỎ THÀNH CÔNG NHẤT (101 - 116)
    "Khủng long mỏ vịt Hadrosaur gặm thực vật bờ sông với chiếc mõm dẹt đặc trưng",
    "Cận cảnh bộ hàm pin nha khoa với hàng trăm chiếc răng nghiền thức ăn liên tục",
    "Parasaurolophus vươn chiếc mào rỗng dài cất tiếng gọi trầm vang khắp thung lũng",
    "Mặt cắt cấu trúc khoang rỗng bên trong mào xương tạo âm cộng hưởng vang xa",
    "Đoàn di cư khổng lồ hàng nghìn cá thể khủng long mỏ vịt rầm rộ qua bình nguyên",
    "Iguanodon đứng thẳng bằng hai chân để lộ chiếc gai nhọn hoắt ở ngón tay cái",
    "Cận cảnh gai ngón cái sắc bén của Iguanodon - Dấu ấn lịch sử ngành cổ sinh",
    "Khu tổ ấp Maiasaura với những bà mẹ khủng long tận tụy chăm sóc từng ổ trứng",
    "Những chú khủng long con bé xíu nở ra từ trứng dưới sự che chở của cha mẹ",
    "Edmontosaurus với chiếc mào thịt mềm mại trên đỉnh đầu đứng giữa rừng rậm",
    "Bảng so sánh muôn hình vạn trạng các kiểu mào đầu độc đáo của họ Hadrosaur",
    "Sóng âm trầm hùng lan tỏa từ mào các chú Parasaurolophus trong buổi hoàng hôn",
    "Khủng long mỏ vịt phi nước đại bằng hai chân sau tung bụi trốn chạy kẻ săn mồi",
    "Bản vẽ phục dựng sai lầm thế kỷ 19 gắn nhầm gai ngón cái thành sừng trên mũi",
    "Bầy Ornithopoda gặm cỏ thanh bình bên dòng sông lấp lánh ánh nắng chiều tà",
    "Bộ xương hóa thạch khủng long mỏ vịt với chiếc mào hoàn mỹ trưng bày trang trọng",

    # PHẦN 9 — NHÓM PACHYCEPHALOSAURIA: CHIẾN BINH ĐẦU CỨNG (117 - 126)
    "Pachycephalosaurus cảnh giác đứng thẳng với vòm sọ tròn cứng như đá hoa cương",
    "Cận cảnh vòm đầu xương dày đặc bao quanh bởi những gai xương nhọn li ti",
    "Hai chàng Pachycephalosaurus lao vào húc đầu chan chát tạo tiếng vang chấn động",
    "Sơ đồ mặt cắt hộp sọ cho thấy lớp xương vòm đỉnh đầu dày đặc đến hai mươi phân",
    "Họ hàng gai góc Stygimoloch với vương miện gai nhọn hoắt xung quanh vòm đầu",
    "Hành vi húc sườn đối kháng - Một giả thuyết cơ sinh học hiện đại về lối giao đấu",
    "Pachycephalosaurus thoăn thoắt chạy bằng hai chân lướt qua tán rừng rậm rạp",
    "Nhóm nhỏ khủng long đầu cứng vừa đi vừa gật gù tìm kiếm chồi non và hạt cây",
    "Dáng dấp chiếc vòm đầu độc nhất vô nhị in bóng nổi bật trên nền trời tiền sử",
    "Mặt cắt hóa thạch vòm sọ Pachycephalosaurus chứng minh độ dày kinh ngạc",

    # PHẦN 10 — NHỮNG NGƯỜI HÀNG XÓM KHÔNG PHẢI KHỦNG LONG (127 - 138)
    "Thằn lằn bay Pteranodon sải cánh khổng lồ lượn gió trên vách đá biển cuộn sóng",
    "Cận cảnh màng cánh dai như da thuộc và các ngón tay vuốt của thằn lằn bay",
    "Bầy Pterodactylus nhỏ nhắn chao liệng duyên dáng trên bờ biển lúc hoàng hôn",
    "Quetzalcoatlus khổng lồ - Sinh vật bay lớn nhất lịch sử đứng cạnh hươu cao cổ",
    "Thương long Mosasaurus vọt lên khỏi mặt nước đớp mồi tạo làn sóng nước dữ dội",
    "Cận cảnh mái chèo bơi khỏe khoắn và đuôi cá mập mạnh mẽ của Mosasaurus",
    "Thằn lằn cổ dài Plesiosaurus uốn lượn chiếc cổ dài mềm mại trong lòng biển xanh",
    "Ngư long Ichthyosaurus hình dáng cá heo lướt đi siêu tốc trong đại dương mở",
    "Cảnh săn đuổi ngoạn mục: Mosasaurus há ngoạm nuốt trọn cúc đá Ammonite cuộn tròn",
    "Bố cục chia ba tầng sinh thái: Bầu trời thằn lằn bay, mặt đất khủng long, biển cả bò sát",
    "Hóa thạch cánh xương mỏng manh tinh xảo của thằn lằn bay lưu giữ trong phiến đá",
    "Plesiosaurus nhô chiếc cổ dài cao vút lên khỏi mặt biển bên rạn đá hoang sơ",

    # PHẦN 11 — SỰ TUYỆT CHỦNG: BUỔI SÁNG ĐỊNH MỆNH (139 - 152)
    "Thiên thạch lửa khổng lồ xé toạc bầu khí quyển lao thẳng xuống bán đảo Yucatan",
    "Vụ nổ va chạm kinh thiên động địa tạo quầng sáng mù lòa và sóng xung kích hủy diệt",
    "Miệng hố va chạm Chicxulub khổng lồ đường kính hai trăm cây số đỏ rực đá nóng chảy",
    "Cơn đại hồng thủy sóng thần cuồn cuộn ập vào bờ cuốn phăng muôn loài tháo chạy",
    "Cháy rừng diện rộng thiêu rụi hàng nghìn cây số vuông, khói đen che kín bầu trời",
    "Mưa hạt thủy tinh nóng chảy trút xuống dòng sông khiến đàn cá Tanis chết ngạt",
    "Nhà địa chất khai quật vỉa đất ranh giới K-Pg mỏng manh ghi dấu ngày tận thế",
    "Bầu trời đen đặc khói bụi lưu huỳnh bóp nghẹt ánh sáng, vạn vật chìm vào suy tàn",
    "Mùa đông va chạm băng giá bao trùm địa cầu, thảm thực vật chết khô vì thiếu nắng",
    "Chú Triceratops cô độc đứng trơ trọi giữa hoang mạc tro tàn lạnh lẽo vô vọng",
    "Bản đồ địa cầu mô phỏng làn sóng chấn động và tro bụi bao phủ kín hành tinh",
    "Lớp địa tầng chứa hàm lượng Iridium cao bất thường minh chứng vụ va chạm vũ trụ",
    "Thung lũng hoang tàn phủ đầy tro xám nơi từng là thiên đường xanh tốt của muôn loài",
    "Bức tranh đối lập nghiệt ngã: Rừng rậm rực rỡ trước va chạm và bình địa tro tàn sau đó",

    # PHẦN 12 — TẠI SAO CÓ LOÀI SỐNG SÓT (153 - 162)
    "Thú có vú nhỏ lông lá ẩn nấp an toàn sâu trong hang đất giữa thảm họa",
    "Khủng long nhỏ có lông dạng chim nép mình trú ẩn trong khe nứt vách đá",
    "Cá sấu cổ kiên cường ngâm mình dưới bùn lầy sống sót qua ngày tuyệt diệt",
    "Biểu tượng sinh tồn: Sinh vật nhỏ bé sống sót đối lập bóng khủng long khổng lồ lụi tàn",
    "Chú chim nguyên thủy nhỏ bới tìm hạt cây tích trữ trong lớp tro lạnh để sinh tồn",
    "Cụ rùa nước ngọt từ từ trồi lên từ lớp bùn đáy hồ sau cơn biến động toàn cầu",
    "Cán cân sinh thái: Động vật cỡ lớn cạn kiệt thức ăn nhường chỗ cho giống loài nhỏ",
    "Sinh vật có vú bé nhỏ rụt rè rời hang bước ra đón ánh bình minh ấm áp đầu tiên",
    "Cây dương xỉ kiên cường đâm chồi xanh mướt trên nền đất tro tàn bắt đầu hồi sinh",
    "Đàn chim cổ vỗ cánh bay lên trên vùng đất xanh tươi đang từng bước phục hồi",

    # PHẦN 13 — TỔNG KẾT: DI SẢN BẤT DIỆT (163 - 170)
    "Hình ảnh biến chuyển kỳ diệu từ khủng long lông vũ Theropod thành chim sẻ hiện đại",
    "Đàn chim hiện đại tung cánh bay rợp trời mang theo dòng máu kiêu hùng của tổ tiên",
    "Đại sảnh danh vọng: Bóng hình các nhóm khủng long thống trị hội tụ đầy tráng lệ",
    "Chú chim sẻ nhỏ nhắn cất tiếng hót trên cành cây - Hậu duệ sống động của khủng long",
    "Dòng thời gian nối liền từ bước chân bạo chúa đến sải cánh chim muôn triệu năm",
    "Du khách trang nghiêm chiêm ngưỡng các bộ xương khủng long khổng lồ trong bảo tàng",
    "Toàn cảnh đại kỷ Trung sinh tráng lệ: Bản trường ca huy hoàng nhất của sự sống",
    "Chiếc lông vũ phát sáng chuyển hóa từ vảy da cổ đại thành đôi cánh bay vút trời cao"
]
